title: "Synergize"
description: "Synergy Librarian and Editor"
remote_theme: pmarsceill/just-the-docs
color_scheme: "midnight"

exclude: ["midi", "go.*","*.log","*.wxs","*.go", "debug-logs", "testbin", "resources", "output", "packages", "uitest", "test", "synio", "cmd", "data", "dx2syn", "README.md", "TESTPLAN.md", "CHECKLIST.md", "TODO.md"  ]

logo: "https://github.com/chinenual/synergize/raw/master/docs/screenshots/logo-for-github.png?raw=true"

aux_links:
  "Home":
  - /synergize
  "User Manual":
  - /synergize/docs
  "Download":
  - https://github.com/chinenual/synergize/releases
  "Github Project":
  - https://github.com/chinenual/synergize

aux_links_new_tab: false

baseurl: "/synergize" 
url: "https://chinenual.github.io" 
