// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * @readonly
 * @enum {number}
 */
export const TrackPlayMode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    PlayModeOff: 0,
    PlayModeOn: 1,
    PlayModeRepeat: 2,
};
