// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as data$0 from "./data/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as zeroconf$0 from "./zeroconf/models.js";

export class ConnectSynergyResponseType {
    /**
     * Creates a new ConnectSynergyResponseType instance.
     * @param {Partial<ConnectSynergyResponseType>} [$$source = {}] - The source object to create the ConnectSynergyResponseType.
     */
    constructor($$source = {}) {
        if (!("AlreadyConnected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AlreadyConnected"] = false;
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {ConnectionStatusResponse}
             */
            this["Status"] = (new ConnectionStatusResponse());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectSynergyResponseType instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectSynergyResponseType}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Status" in $$parsedSource) {
            $$parsedSource["Status"] = $$createField1_0($$parsedSource["Status"]);
        }
        return new ConnectSynergyResponseType(/** @type {Partial<ConnectSynergyResponseType>} */($$parsedSource));
    }
}

export class ConnectionStatusResponse {
    /**
     * Creates a new ConnectionStatusResponse instance.
     * @param {Partial<ConnectionStatusResponse>} [$$source = {}] - The source object to create the ConnectionStatusResponse.
     */
    constructor($$source = {}) {
        if (!("SynergyName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SynergyName"] = "";
        }
        if (!("ControlSurfaceName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ControlSurfaceName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStatusResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionStatusResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionStatusResponse(/** @type {Partial<ConnectionStatusResponse>} */($$parsedSource));
    }
}

/**
 * PayloadDir represents a dir payload
 */
export class Dir {
    /**
     * Creates a new Dir instance.
     * @param {Partial<Dir>} [$$source = {}] - The source object to create the Dir.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Dir instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Dir}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Dir(/** @type {Partial<Dir>} */($$parsedSource));
    }
}

/**
 * Exploration represents the results of an exploration
 */
export class Exploration {
    /**
     * Creates a new Exploration instance.
     * @param {Partial<Exploration>} [$$source = {}] - The source object to create the Exploration.
     */
    constructor($$source = {}) {
        if (!("dirs" in $$source)) {
            /**
             * @member
             * @type {Dir[]}
             */
            this["dirs"] = [];
        }
        if (!("SYNfiles" in $$source)) {
            /**
             * @member
             * @type {Dir[]}
             */
            this["SYNfiles"] = [];
        }
        if (!("CRTfiles" in $$source)) {
            /**
             * @member
             * @type {Dir[]}
             */
            this["CRTfiles"] = [];
        }
        if (!("VCEfiles" in $$source)) {
            /**
             * @member
             * @type {Dir[]}
             */
            this["VCEfiles"] = [];
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Exploration instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Exploration}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dirs" in $$parsedSource) {
            $$parsedSource["dirs"] = $$createField0_0($$parsedSource["dirs"]);
        }
        if ("SYNfiles" in $$parsedSource) {
            $$parsedSource["SYNfiles"] = $$createField1_0($$parsedSource["SYNfiles"]);
        }
        if ("CRTfiles" in $$parsedSource) {
            $$parsedSource["CRTfiles"] = $$createField2_0($$parsedSource["CRTfiles"]);
        }
        if ("VCEfiles" in $$parsedSource) {
            $$parsedSource["VCEfiles"] = $$createField3_0($$parsedSource["VCEfiles"]);
        }
        return new Exploration(/** @type {Partial<Exploration>} */($$parsedSource));
    }
}

export class GetSynergyReturnType {
    /**
     * Creates a new GetSynergyReturnType instance.
     * @param {Partial<GetSynergyReturnType>} [$$source = {}] - The source object to create the GetSynergyReturnType.
     */
    constructor($$source = {}) {
        if (!("HasDevice" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["HasDevice"] = false;
        }
        if (!("AlreadyConfigured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AlreadyConfigured"] = false;
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Choices" in $$source)) {
            /**
             * @member
             * @type {zeroconf$0.Service[] | null}
             */
            this["Choices"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetSynergyReturnType instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GetSynergyReturnType}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Choices" in $$parsedSource) {
            $$parsedSource["Choices"] = $$createField3_0($$parsedSource["Choices"]);
        }
        return new GetSynergyReturnType(/** @type {Partial<GetSynergyReturnType>} */($$parsedSource));
    }
}

export class Preferences {
    /**
     * Creates a new Preferences instance.
     * @param {Partial<Preferences>} [$$source = {}] - The source object to create the Preferences.
     */
    constructor($$source = {}) {
        if (!("LibraryPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LibraryPath"] = "";
        }
        if (!("OscAutoConfig" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["OscAutoConfig"] = false;
        }
        if (!("OscCSurfaceAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["OscCSurfaceAddress"] = "";
        }
        if (!("OscCSurfacePort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["OscCSurfacePort"] = 0;
        }
        if (!("OscPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["OscPort"] = 0;
        }
        if (!("SerialBaud" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["SerialBaud"] = 0;
        }
        if (!("SerialPort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SerialPort"] = "";
        }
        if (!("SerialFlowControl" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["SerialFlowControl"] = false;
        }
        if (!("UseOsc" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["UseOsc"] = false;
        }
        if (!("UseSerial" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["UseSerial"] = false;
        }
        if (!("HTTPDebug" in $$source)) {
            /**
             * hidden from user
             * @member
             * @type {boolean}
             */
            this["HTTPDebug"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preferences instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Preferences}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Preferences(/** @type {Partial<Preferences>} */($$parsedSource));
    }
}

export class SetNumOscillatorsResultType {
    /**
     * Creates a new SetNumOscillatorsResultType instance.
     * @param {Partial<SetNumOscillatorsResultType>} [$$source = {}] - The source object to create the SetNumOscillatorsResultType.
     */
    constructor($$source = {}) {
        if (!("EnvelopeTemplate" in $$source)) {
            /**
             * @member
             * @type {data$0.Envelope}
             */
            this["EnvelopeTemplate"] = (new data$0.Envelope());
        }
        if (!("PatchBytes" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["PatchBytes"] = Array.from({ length: 16 }, () => 0);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetNumOscillatorsResultType instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SetNumOscillatorsResultType}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("EnvelopeTemplate" in $$parsedSource) {
            $$parsedSource["EnvelopeTemplate"] = $$createField0_0($$parsedSource["EnvelopeTemplate"]);
        }
        return new SetNumOscillatorsResultType(/** @type {Partial<SetNumOscillatorsResultType>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ConnectionStatusResponse.createFrom;
const $$createType1 = Dir.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = zeroconf$0.Service.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = data$0.Envelope.createFrom;
