// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as data$0 from "./data/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as seq$0 from "./seq/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as zeroconf$0 from "./zeroconf/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function CancelPreferences() {
    return $Call.ByID(783251701);
}

/**
 * @param {boolean} synergyWasDisconnected
 * @param {boolean} controlSurfaceWasDisconnected
 * @returns {$CancellablePromise<void>}
 */
export function CheckVersion(synergyWasDisconnected, controlSurfaceWasDisconnected) {
    return $Call.ByID(3351173503, synergyWasDisconnected, controlSurfaceWasDisconnected);
}

/**
 * @param {data$0.CRT} crt
 * @param {string} vcePath
 * @param {number} slot
 * @returns {$CancellablePromise<data$0.CRT>}
 */
export function CrtEditAddVoice(crt, vcePath, slot) {
    return $Call.ByID(2539128045, crt, vcePath, slot).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {data$0.CRT} crt
 * @returns {$CancellablePromise<void>}
 */
export function CrtEditLoadCRT(crt) {
    return $Call.ByID(3272049917, crt);
}

/**
 * @param {string} path
 * @param {data$0.CRT} crt
 * @returns {$CancellablePromise<void>}
 */
export function CrtEditSaveCRT(path, crt) {
    return $Call.ByID(4178257586, path, crt);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Dx2synCancel() {
    return $Call.ByID(3057982693);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function Dx2synStart(path) {
    return $Call.ByID(2164463121, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<$models.Exploration>}
 */
export function Explore(path) {
    return $Call.ByID(127536374, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<[string, $models.Preferences]>}
 */
export function GetPreferences() {
    return $Call.ByID(3682233165).then(/** @type {($result: any) => any} */(($result) => {
        $result[1] = $$createType2($result[1]);
        return $result;
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<seq$0.TrackPlayMode[]>}
 */
export function GetSynSequencerState(path) {
    return $Call.ByID(2709634891, path);
}

/**
 * @returns {$CancellablePromise<[string, boolean]>}
 */
export function GetVersion() {
    return $Call.ByID(1744344967);
}

/**
 * @param {$models.Preferences} preferences
 * @returns {$CancellablePromise<void>}
 */
export function SavePreferences(preferences) {
    return $Call.ByID(1411312828, preferences);
}

/**
 * @param {number} uiFilterIndex
 * @param {number[]} values
 * @returns {$CancellablePromise<void>}
 */
export function SetFilterArray(uiFilterIndex, values) {
    return $Call.ByID(1951657392, uiFilterIndex, values);
}

/**
 * @param {number} uiFilterIndex
 * @param {number} index
 * @param {number} value
 * @returns {$CancellablePromise<void>}
 */
export function SetFilterEle(uiFilterIndex, index, value) {
    return $Call.ByID(3725700453, uiFilterIndex, index, value);
}

/**
 * @param {number} index
 * @param {number} value
 * @returns {$CancellablePromise<void>}
 */
export function SetVoiceKPROPEle(index, value) {
    return $Call.ByID(1100869349, index, value);
}

/**
 * @param {number} index
 * @param {number} value
 * @returns {$CancellablePromise<void>}
 */
export function SetVoiceVEQEle(index, value) {
    return $Call.ByID(1799679745, index, value);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowPreferences() {
    return $Call.ByID(1246494516);
}

/**
 * @param {string} path
 * @param {number} tempo
 * @param {boolean} raw
 * @param {number} maxClockSeconds
 * @param {seq$0.TrackPlayMode[]} trackButtons
 * @returns {$CancellablePromise<void>}
 */
export function Syn2midi(path, tempo, raw, maxClockSeconds, trackButtons) {
    return $Call.ByID(2966877142, path, tempo, raw, maxClockSeconds, trackButtons);
}

/**
 * @param {boolean} mode
 * @param {boolean} disconnect
 * @param {data$0.VCE | null} useVce
 * @param {zeroconf$0.Service | null} zeroconfSynergy
 * @param {zeroconf$0.Service | null} zeroconfCs
 * @returns {$CancellablePromise<[data$0.VCE | null, boolean, string, string]>}
 */
export function ToggleVoicingMode(mode, disconnect, useVce, zeroconfSynergy, zeroconfCs) {
    return $Call.ByID(4111399143, mode, disconnect, useVce, zeroconfSynergy, zeroconfCs).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType4($result[0]);
        return $result;
    }));
}

// Private type creation functions
const $$createType0 = data$0.CRT.createFrom;
const $$createType1 = $models.Exploration.createFrom;
const $$createType2 = $models.Preferences.createFrom;
const $$createType3 = data$0.VCE.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
