// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as data$0 from "./data/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as seq$0 from "./seq/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as zeroconf$0 from "./zeroconf/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function CancelPreferences() {
    return $Call.ByID(783251701);
}

/**
 * @param {boolean} synergyWasDisconnected
 * @param {boolean} controlSurfaceWasDisconnected
 * @returns {$CancellablePromise<void>}
 */
export function CheckVersion(synergyWasDisconnected, controlSurfaceWasDisconnected) {
    return $Call.ByID(3351173503, synergyWasDisconnected, controlSurfaceWasDisconnected);
}

/**
 * @param {zeroconf$0.Service | null} zeroconfChoice
 * @returns {$CancellablePromise<$models.ConnectSynergyResponseType>}
 */
export function ConnectSynergy(zeroconfChoice) {
    return $Call.ByID(1765205788, zeroconfChoice).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {data$0.CRT} crt
 * @param {string} vcePath
 * @param {number} slot
 * @returns {$CancellablePromise<data$0.CRT>}
 */
export function CrtEditAddVoice(crt, vcePath, slot) {
    return $Call.ByID(2539128045, crt, vcePath, slot).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {data$0.CRT} crt
 * @returns {$CancellablePromise<void>}
 */
export function CrtEditLoadCRT(crt) {
    return $Call.ByID(3272049917, crt);
}

/**
 * @param {string} path
 * @param {data$0.CRT} crt
 * @returns {$CancellablePromise<void>}
 */
export function CrtEditSaveCRT(path, crt) {
    return $Call.ByID(4178257586, path, crt);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function DisableVRAM() {
    return $Call.ByID(2668031727);
}

/**
 * @returns {$CancellablePromise<$models.ConnectionStatusResponse>}
 */
export function DisconnectControlSurface() {
    return $Call.ByID(3150771529).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ConnectionStatusResponse>}
 */
export function DisconnectSynergy() {
    return $Call.ByID(1331345138).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Dx2synCancel() {
    return $Call.ByID(3057982693);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function Dx2synStart(path) {
    return $Call.ByID(2164463121, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<$models.Exploration>}
 */
export function Explore(path) {
    return $Call.ByID(127536374, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ConnectionStatusResponse>}
 */
export function GetConnectionStatus() {
    return $Call.ByID(1635550443).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetPatchTypeNames() {
    return $Call.ByID(594519195).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<[string, $models.Preferences]>}
 */
export function GetPreferences() {
    return $Call.ByID(3682233165).then(/** @type {($result: any) => any} */(($result) => {
        $result[1] = $$createType5($result[1]);
        return $result;
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<seq$0.TrackPlayMode[]>}
 */
export function GetSynSequencerState(path) {
    return $Call.ByID(2709634891, path);
}

/**
 * @returns {$CancellablePromise<$models.GetSynergyReturnType[]>}
 */
export function GetSynergy() {
    return $Call.ByID(217972966).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.GetSynergyReturnType[]>}
 */
export function GetSynergyAndControlSurface() {
    return $Call.ByID(489125899).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<[string, boolean]>}
 */
export function GetVersion() {
    return $Call.ByID(1744344967);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function LoadSYN(path) {
    return $Call.ByID(748956647, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<data$0.CRT>}
 */
export function ReadCRT(path) {
    return $Call.ByID(3388619906, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<data$0.VCE>}
 */
export function ReadVCE(path) {
    return $Call.ByID(1296091671, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RescanZeroconf() {
    return $Call.ByID(1156182939);
}

/**
 * @param {$models.Preferences} preferences
 * @returns {$CancellablePromise<void>}
 */
export function SavePreferences(preferences) {
    return $Call.ByID(1411312828, preferences);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SaveSYN(path) {
    return $Call.ByID(3370937748, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SaveVCE(path) {
    return $Call.ByID(2968353300, path);
}

/**
 * @param {string} field
 * @param {number} value
 * @returns {$CancellablePromise<void>}
 */
export function SendToCSurface(field, value) {
    return $Call.ByID(1372072484, field, value);
}

/**
 * @param {string} funcname
 * @param {number} osc
 * @param {number} index
 * @param {number} value
 * @returns {$CancellablePromise<void>}
 */
export function SetEnvEle(funcname, osc, index, value) {
    return $Call.ByID(2889952252, funcname, osc, index, value);
}

/**
 * @param {number} osc
 * @param {data$0.Envelope} envelopes
 * @returns {$CancellablePromise<void>}
 */
export function SetEnvelopes(osc, envelopes) {
    return $Call.ByID(3628011926, osc, envelopes);
}

/**
 * @param {number} uiFilterIndex
 * @param {number[]} values
 * @returns {$CancellablePromise<void>}
 */
export function SetFilterArray(uiFilterIndex, values) {
    return $Call.ByID(1951657392, uiFilterIndex, values);
}

/**
 * @param {number} uiFilterIndex
 * @param {number} index
 * @param {number} value
 * @returns {$CancellablePromise<void>}
 */
export function SetFilterEle(uiFilterIndex, index, value) {
    return $Call.ByID(3725700453, uiFilterIndex, index, value);
}

/**
 * @param {number} osc
 * @param {string} env
 * @param {number} envType
 * @param {number} sustainPt
 * @param {number} loopPt
 * @returns {$CancellablePromise<void>}
 */
export function SetLoopPoint(osc, env, envType, sustainPt, loopPt) {
    return $Call.ByID(1734588703, osc, env, envType, sustainPt, loopPt);
}

/**
 * @param {number} numOsc
 * @param {number} patchType
 * @returns {$CancellablePromise<$models.SetNumOscillatorsResultType>}
 */
export function SetNumOscillators(numOsc, patchType) {
    return $Call.ByID(3797214618, numOsc, patchType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {number} osc
 * @param {number} freqLength
 * @param {number} ampLength
 * @returns {$CancellablePromise<void>}
 */
export function SetOscEnvLengths(osc, freqLength, ampLength) {
    return $Call.ByID(162934356, osc, freqLength, ampLength);
}

/**
 * @param {number[]} args
 * @returns {$CancellablePromise<void>}
 */
export function SetOscFILTER(args) {
    return $Call.ByID(3555546242, args);
}

/**
 * @param {number[]} args
 * @returns {$CancellablePromise<void>}
 */
export function SetOscKEYPROP(args) {
    return $Call.ByID(3332065058, args);
}

/**
 * @param {boolean[]} mute
 * @param {boolean[]} solo
 * @returns {$CancellablePromise<boolean[]>}
 */
export function SetOscSolo(mute, solo) {
    return $Call.ByID(1063518047, mute, solo);
}

/**
 * @param {number[]} args
 * @returns {$CancellablePromise<void>}
 */
export function SetOscWAVE(args) {
    return $Call.ByID(3701878417, args);
}

/**
 * @param {number} index
 * @returns {$CancellablePromise<number[]>}
 */
export function SetPatchType(index) {
    return $Call.ByID(2440239717, index);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SetVNAME(name) {
    return $Call.ByID(474782638, name);
}

/**
 * @param {string} param
 * @param {number[]} args
 * @returns {$CancellablePromise<void>}
 */
export function SetVoiceByte(param, args) {
    return $Call.ByID(1141126583, param, args);
}

/**
 * @param {number} index
 * @param {number} value
 * @returns {$CancellablePromise<void>}
 */
export function SetVoiceKPROPEle(index, value) {
    return $Call.ByID(1100869349, index, value);
}

/**
 * @param {number} osc
 * @param {number} value
 * @returns {$CancellablePromise<void>}
 */
export function SetVoiceOscDataByte(osc, value) {
    return $Call.ByID(2361785606, osc, value);
}

/**
 * @param {number} index
 * @param {number} value
 * @returns {$CancellablePromise<void>}
 */
export function SetVoiceVEQEle(index, value) {
    return $Call.ByID(1799679745, index, value);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowAbout() {
    return $Call.ByID(3434432679);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowPreferences() {
    return $Call.ByID(1246494516);
}

/**
 * @param {string} path
 * @param {number} tempo
 * @param {boolean} raw
 * @param {number} maxClockSeconds
 * @param {seq$0.TrackPlayMode[]} trackButtons
 * @returns {$CancellablePromise<void>}
 */
export function Syn2midi(path, tempo, raw, maxClockSeconds, trackButtons) {
    return $Call.ByID(2966877142, path, tempo, raw, maxClockSeconds, trackButtons);
}

/**
 * @param {boolean} mode
 * @param {boolean} disconnect
 * @param {data$0.VCE | null} useVce
 * @param {zeroconf$0.Service | null} zeroconfSynergy
 * @param {zeroconf$0.Service | null} zeroconfCs
 * @returns {$CancellablePromise<[data$0.VCE | null, boolean, string, string]>}
 */
export function ToggleVoicingMode(mode, disconnect, useVce, zeroconfSynergy, zeroconfCs) {
    return $Call.ByID(4111399143, mode, disconnect, useVce, zeroconfSynergy, zeroconfCs).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType10($result[0]);
        return $result;
    }));
}

// Private type creation functions
const $$createType0 = $models.ConnectSynergyResponseType.createFrom;
const $$createType1 = data$0.CRT.createFrom;
const $$createType2 = $models.ConnectionStatusResponse.createFrom;
const $$createType3 = $models.Exploration.createFrom;
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $models.Preferences.createFrom;
const $$createType6 = $models.GetSynergyReturnType.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = data$0.VCE.createFrom;
const $$createType9 = $models.SetNumOscillatorsResultType.createFrom;
const $$createType10 = $Create.Nullable($$createType8);
