// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as data$0 from "./data/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as zeroconf$0 from "./zeroconf/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function CancelPreferences() {
    return $Call.ByID(783251701);
}

/**
 * @param {boolean} synergyWasDisconnected
 * @param {boolean} controlSurfaceWasDisconnected
 * @returns {$CancellablePromise<void>}
 */
export function CheckVersion(synergyWasDisconnected, controlSurfaceWasDisconnected) {
    return $Call.ByID(3351173503, synergyWasDisconnected, controlSurfaceWasDisconnected);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<$models.Exploration>}
 */
export function Explore(path) {
    return $Call.ByID(127536374, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<[string, $models.Preferences]>}
 */
export function GetPreferences() {
    return $Call.ByID(3682233165).then(/** @type {($result: any) => any} */(($result) => {
        $result[1] = $$createType1($result[1]);
        return $result;
    }));
}

/**
 * @returns {$CancellablePromise<[string, boolean]>}
 */
export function GetVersion() {
    return $Call.ByID(1744344967);
}

/**
 * @param {$models.Preferences} preferences
 * @returns {$CancellablePromise<void>}
 */
export function SavePreferences(preferences) {
    return $Call.ByID(1411312828, preferences);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowPreferences() {
    return $Call.ByID(1246494516);
}

/**
 * @param {boolean} mode
 * @param {boolean} disconnect
 * @param {data$0.VCE | null} useVce
 * @param {zeroconf$0.Service | null} zeroconfSynergy
 * @param {zeroconf$0.Service | null} zeroconfCs
 * @returns {$CancellablePromise<[data$0.VCE | null, boolean, string, string]>}
 */
export function ToggleVoicingMode(mode, disconnect, useVce, zeroconfSynergy, zeroconfCs) {
    return $Call.ByID(4111399143, mode, disconnect, useVce, zeroconfSynergy, zeroconfCs).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType3($result[0]);
        return $result;
    }));
}

// Private type creation functions
const $$createType0 = $models.Exploration.createFrom;
const $$createType1 = $models.Preferences.createFrom;
const $$createType2 = data$0.VCE.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
