// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Service {
    /**
     * Creates a new Service instance.
     * @param {Partial<Service>} [$$source = {}] - The source object to create the Service.
     */
    constructor($$source = {}) {
        if (!("InstanceName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["InstanceName"] = "";
        }
        if (!("HostName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["HostName"] = "";
        }
        if (!("Port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Port"] = 0;
        }
        if (!("Text" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: string }}
             */
            this["Text"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Service instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Service}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Text" in $$parsedSource) {
            $$parsedSource["Text"] = $$createField3_0($$parsedSource["Text"]);
        }
        return new Service(/** @type {Partial<Service>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
