name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: macos-10.14
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        make installDependencies
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: Archive
      uses: actions/upload-artifact@v2
      with:
         name: binaries
         path: ./output/**/*

  uitest:
    name: UITest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: uitest
    strategy:
      matrix:
        os: [ubuntu-16.04]
    steps:

    - name: Unarchive
      uses: actions/download-artifact@v2
      with:
        name: binaries

    - name: SetupNode
      uses: actions/setup-node@v2.1.1

    - name: Run the test
      run: npm test
